const ru = {
  welcome: "Добро пожаловать",
  description: "Этот сайт поддерживает смену языка.",
  home: "Главная страница",
  about: "О нас",
  partners: "Партнеры",
  fastService: "Быстрый сервис",
  phone: "+998 77 404 40 40",
  osago: "ОСАГО",
  travel: "Страхование путешествий",
  accident: "Страхование от несчастных случаев",
  kasko: "КАСКО",
  clearance: "Оформление",
  property: "Имущество",
  sport: "Страхование спортсменов",
  soon: "Скоро",
  heroTitle: "Единый маркетплейс по страхованию <span style='color: black;'>без ограничений на продажу</span>",
  heroDesc: "«Мы не ограничиваемся только продажей страхования»",
  heroBtn: "Войти",
  aboutTitle: "О нас",
  aboutSubtitle: "Инновационные <span style='color: black'>страховые решения</span>",
  aboutDesc: "Этот сайт был создан для настоящей работы страхования, и только продукты надежных страховых компаний продаются через этот сайт.",
  aboutBtn: "Подробнее",
  partnersTitle: "Наши партнеры",
  trustWhy: "Почему вы можете <span style='color: black'>доверять нам?</span>",
  trust1: "Практическая помощь",
  trust1desc: "Гарантируется практическая помощь при возникновении проблем со страховыми услугами и компаниями.",
  trust2: "Отобранные компании",
  trust2desc: "Страховые компании отбираются под контролем опытного страховщика Хасана Холботаева.",
  trust3: "Бесплатная консультация",
  trust3desc: "Для клиентов, купивших страховку, при необходимости предоставляется разовая бесплатная консультация.",
  trust4: "Зона обслуживания",
  trust4desc: "Вся Узбекистан",
  footerSlogan: "Ваш настоящий помощник по страхованию",
  footerHome: "Главная страница",
  footerOsago: "ОСАГО",
  footerTravel: "Путешествия",
  footerPartners: "Партнерство",
  footerSupport: "Поддержка клиентов",
  footerFaq: "Часто задаваемые вопросы",
  footerPrivacy: "Политика конфиденциальности",
  footerCopyright: "© «elsu.uz», 2025. Все права защищены.",
  euro: "Европротокол",
  euroDesc: "Образец заполнения европротокола",
  tow: "Вызов эвакуатора",
  towDesc: "Срочная помощь при ДТП или технической неисправности.",
  fuel: "Бензин",
  fuelDesc: "Закончился бензин в дороге? Нажмите кнопку и закажите доставку топлива (по Ташкенту и области)",
  eval: "Оценка",
  evalDesc: "Нужна оценка ущерба? Нажмите кнопку и свяжитесь с оценщиком",
  use: "Использовать",
  towTitle: "Вызов эвакуатора",
  towDescModal: "Пожалуйста, введите ваше имя, фамилию и номер телефона для связи.",
  towName: "Имя фамилия",
  towPhone: "Номер телефона",
  towSubmit: "Продолжить",
  carNumberPlaceholder: "Гос. номер автомобиля",
  texSeriyaPlaceholder: "Серия",
  texRaqamPlaceholder: "Номер",
  passportSeriyaPlaceholder: "Серия",
  passportRaqamPlaceholder: "Номер",
  osagoFormTitle: "Введите данные",
  osagoFormDesc: "Эти данные необходимы для расчета стоимости обязательного страхового полиса.",
  passportTitle: "Паспортные данные владельца",
  passportDesc: "Для перехода к следующему шагу введите паспортные данные владельца автомобиля",
  summaryTitle: "Ваши данные",
  summaryModel: "Модель авто:",
  summaryNumber: "Гос. номер:",
  callTitle: "Позвоните:",
  signinTitle: "Вход в ",
  signinTitleSpan: "профиль",
  signinCardTitle: "Введите номер телефона для продолжения",
  signinPhonePlaceholder: "77 404 40 40",
  signinCheckboxLabelStart: "Авторизуясь, вы соглашаетесь с ",
  signinPolicyLink: "политикой обработки персональных данных",
  signinCheckboxLabelEnd: "",
  signinBtn: "Продолжить",
  codeModalTitle: "Введите код",
  codeModalDesc: "На номер <span id='modalPhoneNumber'>+998 77 404 40 40</span> отправлен код для подтверждения.",
  timer: "60 секунд",
  confirmBtn: "Подтвердить",
  profileMyData: "Мои данные",
  profileMyInsurances: "Мои страховки",
  osagosugTableTitle: "Мои страховки",
  osagophoneFormLabel: "Введите номер телефона для продолжения",
  osagophoneCallTitle: "Позвоните:",
  logout: "Выйти <img style='margin-left:99px' class='exit-logo' src='/assets/images/exit.svg' alt='Tasdiqlash'>",
  profileId: "ID: 451 458 867",
  profileName: "Имя Фамилия",
  profileBirth: "Дата рождения",
  profilePhone: "Телефон",
  profileGender: "Пол",
  profileMale: "Мужчина",
  profileFemale: "Женщина",
  profileEditTitle: "Изменить личные данные",
  profileSave: "Сохранить",
  profileNamePlaceholder: "Имя Фамилия",
  profilePhonePlaceholder: "Телефон",
  policyInfoTitle: "Информация о полисе",
  policyTypeLabel: "Выберите тип полиса",
  selectChoose: "Выбрать",
  policyTypeUnlimited: "Для неограниченного числа водителей",
  policyTypeLimited: "Для до 5 водителей",
  policyDurationLabel: "Выберите срок страхования",
  policyDuration1y: "1 год",
  policyDuration6m: "6 месяцев",
  policyStartDateLabel: "Выберите дату начала",
  policyCompanyLabel: "Выберите страховую компанию",
  companyEl: "EL SUG'URTA",
  companyIngo: "INGO-UZBEKISTAN",
  companyKapital: "Kapital sug'urta",
  companyNeo: "NEO Insurance",
  policyOfferLink: "согласен с условиями.",
  policySummaryTitle: "Ваш полис",
  policySummaryCompany: "Страховая компания",
  policySummaryAmount: "Страховая сумма",
  summaryFio: "Ф.И.О:",
  relativesInfo: "Информация о близких родственниках <b>Ситризаева Толкина</b>, управляющих автомобилем",
  addBtn: "Добавить",
  continueBtn: "Продолжить",
  summaryDrivers: "Добавленные водители",
  summaryPayment: "Оплата",
  policyInfoModalTitle: "Информация о страховании",
  policyInfoModalAmount1: "26 млн",
  policyInfoModalDesc1: "Максимальная сумма выплаты за вред жизни или здоровью людей при управлении вашим автомобилем",
  policyInfoModalAmount2: "14 млн",
  policyInfoModalDesc2: "Максимальная сумма выплаты за вред имуществу людей при управлении вашим автомобилем",
  relativesInfoModalTitle: "Укажите близких родственников, которые могут управлять автомобилем без вас.",
  relativesInfoModalBody: "Если ваш близкий родственник совершит ДТП, не будучи указанным в страховом полисе, страховая компания не выплатит компенсацию или взыщет выплаченную сумму с неуказанного родственника.",
  tableId: "ID",
  tableName: "Имя Фамилия",
  tableInsurance: "Страховка",
  tableStart: "Начало",
  tableEnd: "Окончание",
  tableDownload: "Скачать",
  tableFio: "Ф.И.О.",
  tablePhone: "Телефон",
  tablePayment: "Оплата",
  tableDrivers: "Добавленные водители",
  paymentMethod: "Выберите способ оплаты:",
  payme: "Payme",
  click: "Click",
};

export default ru;
