const uz = {
  welcome: "Xush kelibsiz",
  description: "Bu sayt tilni o‘zgartirishni qo‘llab-quvvatlaydi.",
  home: "Asosiy sahifa",
  about: "Biz haqimizda",
  partners: "Hamkorlar",
  fastService: "Tezkor xizmat",
  phone: "+998 77 404 40 40",
  osago: "OSAGO",
  travel: "Sayohat sug’urtasi",
  accident: "Baxtsiz hodisalardan sug’urta",
  kasko: "KASKO",
  clearance: "RASMIYLASHTIRISH",
  property: "Mol-Mulk",
  sport: "Sportchilar sug’urtasi",
  soon: "Tez kunda",
  heroTitle: "Sug’urta bo’yicha yagona sotuv bilan cheklanmagan marketplace",
  heroDesc: "“Biz sug’urta sotuvi bilan cheklanmaymiz”",
  heroBtn: "Kirish",
  aboutTitle: "Biz haqimizda",
  aboutSubtitle: "Innovatsion Sug'urta Yechimlari",
  aboutDesc: "Haqiqiy sug’urtaning ishlashini hohlab ushbu sayt ishga tushirildi va bu sayt orqali faqatgina ishonchli sug’urta kompaniyalarning sug’urta mahsulotlari sotuvi amalga oshiriladi.",
  aboutBtn: "Batafsil",
  partnersTitle: "Hamkorlarimiz",
  trustWhy: "Nega bizga ishonishingiz mumkin?",
  trust1: "Amaliy yordam",
  trust1desc: "Taklif etilayotgan sug'urta xizmatlari va taklif etayotgan sug'urta kompaniyalar bilan muammo yuzaga kelsa amaliy yordam kafolatlanadi",
  trust2: "Saralangan kompaniyalar",
  trust2desc: "Tajribali sug'urtachi Hasan Xolbo’tayev nazorati ostida sug’urta kompaniyalar saralanadi",
  trust3: "Bepul konsultatsiya",
  trust3desc: "Sug'urta sotib olgan mijozlar uchun zarur holatda bir martalik bepul konsultatsiya beriladi",
  trust4: "Xizmat ko'rsatish hududi",
  trust4desc: "Butun O'zbekiston",
  footerSlogan: "Sug’urta bo’yicha haqiqiy yordamchingiz",
  footerHome: "Asosiy sahifa",
  footerOsago: "OSAGO",
  footerTravel: "Sayohat",
  footerPartners: "Hamkorlik",
  footerSupport: "Mijozlarni Qo‘llab-Quvvatlash",
  footerFaq: "Tez-tez so‘raladigan savollar",
  footerPrivacy: "Maxfiylik siyosati",
  footerCopyright: "© “elsu.uz”, 2025 Barcha huquqlar himoyalangan.",
  euro: "Yevroprotokol",
  euroDesc: "Yevroprotokol to'ldirish namunasi",
  tow: "Evakuator chaqirish",
  towDesc: "Yo‘l-transport hodisasi yuz berganda yoki texnik nosozlikda tezkor yordam chaqirish xizmati.",
  fuel: "Benzin",
  fuelDesc: "Yo‘lda favqulodda yoqilg‘ingiz tugab qoldimi? Tugmani bosish bilan qo‘ng‘iroq qiling va benzin etkazib berishlarini so‘rang (Toshkent shahri va atrofi bo‘yicha)",
  eval: "Baholash",
  evalDesc: "Zararni baholash kerak bo‘ldimi? Tugmani bosish bilan qo‘ng‘iroq qiling va baholovchi bilan bog‘laning",
  use: "Foydalanish",
  towTitle: "Evakuator chaqirish",
  towDescModal: "Iltimos, siz bilan bog’lanishimiz uchun ism, familiyangiz va telefon raqamingizni kiriting.",
  towName: "Ism familiya",
  towPhone: "Telefon raqam",
  towSubmit: "Davom etish",
  carNumberPlaceholder: "Mashina davlat raqami",
  texSeriyaPlaceholder: "Seriyasi",
  texRaqamPlaceholder: "Raqami",
  passportSeriyaPlaceholder: "Seriya",
  passportRaqamPlaceholder: "Raqami",
  osagoFormTitle: "Ma’lumotlarni kiriting",
  osagoFormDesc: "Ushbu ma’lumotlar majburiy sug‘urta polisining narxini aniqlash uchun kerak.",
  passportTitle: "Mashina egasi pasport ma’lumoti",
  passportDesc: "Keyingi qadamga o‘tish uchun mashina egasining pasport ma’lumotlarini kiriting",
  summaryTitle: "Sizning ma'lumotlaringiz",
  summaryModel: "Mashina modeli:",
  summaryNumber: "Davlat raqami:",
  callTitle: "Qo‘ng‘iroq qiling:",
  signinTitle: "Profilga ",
  signinTitleSpan: "kirish",
  signinCardTitle: "Davom etish uchun telefon raqamingizni kiriting",
  signinPhonePlaceholder: "77 404 40 40",
  signinCheckboxLabelStart: "Avtorizatsiyadan o'tish orqali siz ",
  signinPolicyLink: "shaxsiy ma'lumotlarni qayta ishlash siyosatiga",
  signinCheckboxLabelEnd: " rozilik bildirasiz",
  signinBtn: "Davom etish",
  codeModalTitle: "Kodini kiriting",
  codeModalDesc: "Telefonni tasdiqlash uchun <span id='modalPhoneNumber'>+998 77 404 40 40</span> raqamiga kod yuborildi.",
  timer: "60 Sekund",
  confirmBtn: "Tasdiqlash",
  profileMyData: "Ma'lumotlarim",
  profileMyInsurances: "Sug'urtalarim",
  logout: "Tizimdan chiqish",
  profileId: "ID: 451 458 867",
  profileName: "Ism Familiya",
  profileBirth: "Tug‘ilgan sana",
  profilePhone: "Telefon raqam",
  profileGender: "Jins",
  profileMale: "Erkak",
  profileFemale: "Ayol",
  profileEditTitle: "Shaxsiy ma'lumotlarni o'zgartirish",
  profileSave: "Saqlash",
  profileNamePlaceholder: "Ism Familiya",
  profilePhonePlaceholder: "Telefon raqam",
  policyInfoTitle: "Polis ma'lumotlari",
  policyTypeLabel: "Polis turini tanlang",
  selectChoose: "Tanlang",
  policyTypeUnlimited: "Cheklanmagan haydovchilar uchun",
  policyTypeLimited: "5 nafargacha haydovchilar uchun",
  policyDurationLabel: "Sug'urta muddatini tanlang",
  policyDuration1y: "1 yil",
  policyDuration6m: "6 oy",
  policyStartDateLabel: "Boshlanish sanasini tanlang",
  policyCompanyLabel: "Sug'urta kompaniyasini tanlang",
  companyEl: "EL SUG'URTA",
  companyIngo: "INGO-UZBEKISTAN",
  companyKapital: "Kapital sug'urta",
  companyNeo: "NEO Insurance",
  policyOfferLink: "shartlariga roziman.",
  policySummaryTitle: "Sizning polisingiz",
  policySummaryCompany: "Sug'urta kompaniyasi",
  policySummaryAmount: "Sug'urta summasi",
  summaryFio: "F.I.Sh:",
  relativesInfo: "Avtomobilni boshqaradigan <b>Sitrizaev To‘lqin</b>ning yaqin qarindoshlari haqida ma’lumot",
  addBtn: "Qo'shish",
  continueBtn: "Davom etish",
  summaryDrivers: "Qo‘shilgan haydovchilar",
  summaryPayment: "To‘lov",
  policyInfoModalTitle: "Sug'urta ma'lumotlari",
  policyInfoModalAmount1: "26 mln",
  policyInfoModalDesc1: "Mashinaingizni boshqarayotganingizda insonlarning sog'ligi yoki hayotiga zarar yetkazilganligi uchun maksimal to'lov miqdori",
  policyInfoModalAmount2: "14 mln",
  policyInfoModalDesc2: "Mashinaingizni boshqarayotganingizda insonlarning mol-mulkiga zarar yetkazilganligi uchun maksimal to'lov miqdori",
  relativesInfoModalTitle: "Avtomobilingizni Sizsiz ham boshqaradigan yaqin qarindoshlaringizni kiriting.",
  relativesInfoModalBody: "Agar yaqin qarindoshingiz sug‘urta polisda ko‘rsatilmagan holatda YTH sodir qilsa sug‘urta kompaniyasi ushbu holat uchun to‘lov amalga oshirmaydi yoki to‘lov qilib bersa ham. Qilingan to‘lovlarni sug‘urtadan ko‘rsatilmagan yaqin qarindoshingizdan undirib oladi.",
};

export default uz;
